ALTER TABLE IF EXISTS gateway_routes
    DROP COLUMN IF EXISTS body_size_limit,
    DROP COLUMN IF EXISTS proxy_send_timeout_seconds,
    DROP COLUMN IF EXISTS proxy_read_timeout_seconds,
    DROP COLUMN IF EXISTS preserve_host,
    DROP COLUMN IF EXISTS strip_path_prefix,
    DROP COLUMN IF EXISTS ingress_annotations,
    DROP COLUMN IF EXISTS response_headers,
    DROP COLUMN IF EXISTS request_headers,
    DROP COLUMN IF EXISTS ingress_class_name;

ALTER TABLE IF EXISTS runtime_clusters
    DROP COLUMN IF EXISTS gateway_default_response_headers,
    DROP COLUMN IF EXISTS gateway_default_request_headers,
    DROP COLUMN IF EXISTS gateway_trusted_proxy_cidrs,
    DROP COLUMN IF EXISTS gateway_forwarded_headers_mode,
    DROP COLUMN IF EXISTS gateway_external_tls_mode,
    DROP COLUMN IF EXISTS gateway_ingress_class_name,
    DROP COLUMN IF EXISTS gateway_controller_type;
