import type { ComponentType, SVGProps } from 'react'
import {
  AppWindow,
  BarChart3,
  Bell,
  Bot,
  Box,
  Calendar,
  ChartLine,
  Cloud,
  Container,
  Cpu,
  CreditCard,
  Database,
  FileText,
  FolderKanban,
  GitBranch,
  Globe,
  KeyRound,
  LayoutDashboard,
  LockKeyhole,
  Mail,
  MessageSquare,
  Network,
  Package,
  Rocket,
  Server,
  Settings,
  Shield,
  ShoppingCart,
  Terminal,
  Users,
  Workflow,
  Zap,
} from 'lucide-react'

export type IconComponent = ComponentType<SVGProps<SVGSVGElement>>

export const APPLICATION_ICON_NAMES = [
  'box',
  'app-window',
  'layout-dashboard',
  'server',
  'database',
  'cpu',
  'cloud',
  'globe',
  'network',
  'shield',
  'lock-keyhole',
  'key-round',
  'shopping-cart',
  'credit-card',
  'chart-line',
  'bar-chart-3',
  'message-square',
  'mail',
  'bell',
  'calendar',
  'file-text',
  'folder-kanban',
  'git-branch',
  'terminal',
  'workflow',
  'package',
  'container',
  'rocket',
  'zap',
  'bot',
  'users',
  'settings',
] as const

export type ApplicationIconName = typeof APPLICATION_ICON_NAMES[number]

export const applicationIconComponents: Record<ApplicationIconName, IconComponent> = {
  'app-window': AppWindow,
  'bar-chart-3': BarChart3,
  'bell': Bell,
  'bot': Bot,
  'box': Box,
  'calendar': Calendar,
  'chart-line': ChartLine,
  'cloud': Cloud,
  'container': Container,
  'cpu': Cpu,
  'credit-card': CreditCard,
  'database': Database,
  'file-text': FileText,
  'folder-kanban': FolderKanban,
  'git-branch': GitBranch,
  'globe': Globe,
  'key-round': KeyRound,
  'layout-dashboard': LayoutDashboard,
  'lock-keyhole': LockKeyhole,
  'mail': Mail,
  'message-square': MessageSquare,
  'network': Network,
  'package': Package,
  'rocket': Rocket,
  'server': Server,
  'settings': Settings,
  'shield': Shield,
  'shopping-cart': ShoppingCart,
  'terminal': Terminal,
  'users': Users,
  'workflow': Workflow,
  'zap': Zap,
}

export function isApplicationIconName(value: string): value is ApplicationIconName {
  return APPLICATION_ICON_NAMES.includes(value as ApplicationIconName)
}

export function normalizeApplicationIconName(value?: string) {
  return value && isApplicationIconName(value) ? value : 'box'
}
