apiVersion: v2
name: luna-devops
description: Luna DevOps application delivery platform.
type: application
version: 0.1.0
appVersion: nightly
home: https://github.com/LiteyukiStudio/devops
sources:
  - https://github.com/LiteyukiStudio/devops
maintainers:
  - name: Luna DevOps
keywords:
  - devops
  - kubernetes
  - buildkit
  - deployment
