const appTemplatesPage = {
  description: 'Install common infrastructure apps such as Redis, PostgreSQL, and MySQL from presets.',
  heroTitle: 'App Marketplace',
  heroDescription: 'Pick a built-in template, fill in a few values, and install it into a project space. The platform creates the application, deployment target, and optional first release.',
  searchPlaceholder: 'Search templates, images, or categories',
  loading: 'Loading app templates...',
  emptyTitle: 'No templates found',
  emptyDescription: 'Try another keyword, or wait for administrators to add more templates.',
  install: 'Install',
  installing: 'Installing...',
  installStarted: 'App template installation started',
  installDialogTitle: 'Install {{name}}',
  installDialogDescription: 'The template creates an application and deployment target in the selected project space. Secret values are stored securely and are not echoed back.',
  runtimeCluster: 'Runtime Cluster',
  defaultCluster: 'Use default cluster',
  applicationName: 'Application Name',
  applicationSlug: 'Application Slug',
  deploymentName: 'Deployment Target',
  stage: 'Stage',
  replicas: 'Replicas',
  cpu: 'CPU',
  memory: 'Memory',
  dataCapacity: 'Data Capacity',
  templateParameters: 'Template Parameters',
  templateParametersDescription: 'Empty auto-generated secrets are generated by the backend and written into the secret store.',
  autoGeneratePlaceholder: 'Leave empty to auto-generate',
  installNow: 'Deploy after install',
  installNowDescription: 'When disabled, the application and deployment target are created only. You can release manually from the application deployment page.',
  image: 'Image',
  port: 'Port',
  resources: 'Resources',
  categories: {
    database: 'Database',
    middleware: 'Middleware',
  },
  stageOptions: {
    prod: 'Production',
    staging: 'Staging',
    test: 'Test',
    dev: 'Development',
  },
  valueLabels: {
    username: 'Username',
    database: 'Database',
    password: 'Password',
    rootPassword: 'Root Password',
  },
  templates: {
    redis: {
      description: 'In-memory data store for cache, queues, and lightweight coordination.',
    },
    postgresql: {
      description: 'Relational database for application data, metadata, and transactional workloads.',
    },
    mysql: {
      description: 'Classic relational database with a simple single-container setup.',
    },
    rabbitmq: {
      description: 'Message broker for asynchronous jobs, events, and lightweight queues.',
    },
  },
}

export default appTemplatesPage
